name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc

      - name: Add .env file
        run: |
          touch .env
          echo "${{ secrets.PRD_ENV }}" > .env

      # - name: Install pnpm and dependencies
      #   run: |
      #     npm install -g pnpm
      #     pnpm install

      # - name: Kill existing pm2 process
      #   run: pm2 kill

      # - name: Build & Run Development Server
      #   run: pnpm start:prod
